<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6FQI5GQB" failures="0" tests="4" name="Default test" time="0.755" errors="0" timestamp="2022-04-21T22:17:53 ICT">
  <testcase classname="TaiKhoanTest" name="@BeforeTest checkLoginSuccess" time="0.7">
    <failure type="java.lang.IllegalStateException" message="Cannot get a NUMERIC value from a STRING cell">
      <![CDATA[java.lang.IllegalStateException: Cannot get a NUMERIC value from a STRING cell
at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1022)
at org.apache.poi.xssf.usermodel.XSSFCell.getNumericCellValue(XSSFCell.java:319)
at excel.ReadWriteTaiKhoan.ReadFileExcell(ReadWriteTaiKhoan.java:48)
at TaiKhoanTest.checkLoginSuccess(TaiKhoanTest.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest checkLoginSuccess -->
  <testcase classname="TaiKhoanTest" name="findUserByUserName" time="0.0">
    <skipped/>
  </testcase> <!-- findUserByUserName -->
  <testcase classname="TaiKhoanTest" name="addUser" time="0.0">
    <skipped/>
  </testcase> <!-- addUser -->
  <testcase classname="TaiKhoanTest" name="updateUser" time="0.0">
    <skipped/>
  </testcase> <!-- updateUser -->
  <testcase classname="TaiKhoanTest" name="deleteUser" time="0.0">
    <skipped/>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- Default test -->
